### ISSUE TITLE
youtubeを見ながらやってみる

### ISSUE THREAD

**Issue by soudegesu** [soudegesu/demo-java-9-migration#1]
↓の動画を見ながら動かしてみる
https://www.youtube.com/watch?v=NKY2FYTCo7I

**Comment by soudegesu** [comment]
[準備]
java9をoracleからダウンロードし、インストールする
http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html

ダウンロードしたのは、 `jdk-9.0.1_osx-x64_bin.dmg`

**Comment by soudegesu** [comment]
` java -version` で確認するとローカルマシン上が全てjava9になってしまうので、以下のように `.zshrc` に記載をして `source` する

```
export JAVA_HOME=`/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java_home -v "1.8"`
```

**Comment by soudegesu** [comment]
もとに戻った

```
java -version
>java version "1.8.0_144"
>Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
>Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by soudegesu** [comment]
まずはjava8のまま、mvnコマンドがきちんと動作することを確認する
```
mvn clean install
```

**Comment by soudegesu** [comment]
successしました

**Comment by soudegesu** [comment]
runしてみる
```
java -cp 'monitor/target/libs/*':'monitor/target/main-1.0-SNAPSHOT.jar' monitor.Main
```

**Comment by soudegesu** [comment]
successしました

**Comment by soudegesu** [comment]
一応、mavenも確認する
```
mvn --version
>Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-12T05:58:10+09:00)
>Maven home: /usr/local/Cellar/maven/3.2.3/libexec
>Java version: 1.8.0_144, vendor: Oracle Corporation
>Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
>Default locale: ja_JP, platform encoding: UTF-8
>OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"
```

**Comment by soudegesu** [comment]
mvnのruntimeをjava9に変えてあげる必要がありそうだ

**Comment by soudegesu** [comment]
`mvn` のときだけ java9を使用するように変更する

```
vi ~/.mavenrc
```

以下を追記
```
JAVA_HOME=`/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java_home -v "9"`
```

**Comment by soudegesu** [comment]
確認する
```
mvn --version

Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-12T05:58:10+09:00)
Maven home: /usr/local/Cellar/maven/3.2.3/libexec
Java version: 9.0.1, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
Default locale: ja_JP, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"
```

**Comment by soudegesu** [comment]
IntelliJでこのプロジェクトをimportする
importするときにはjdk9をコンパイラにして、mavenプロジェクトとして扱う

**Comment by soudegesu** [comment]
`pom.xml` に以下を追記して `mvn clean install`

```
	<profiles>
		<profile>
			<id>java-9</id>
			<activation>
				<jdk>9</jdk>
			</activation>
			<properties>
				<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
				<maven.compiler.release>9</maven.compiler.release>
			</properties>
		</profile>
	</profiles>
```

**Comment by soudegesu** [comment]
エラーになった

**Comment by soudegesu** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project utils: Compilation failure: Compilation failure:
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.utils/src/main/java/monitor/utils/Utils.java:[3,15] エラー: シンボルを見つけられません
[ERROR] シンボル:   クラス BASE64Encoder
[ERROR] 場所: パッケージ sun.misc
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.utils/src/main/java/monitor/utils/Utils.java:[25,13] エラー: シンボルを見つけられません
[ERROR] シンボル:   クラス BASE64Encoder
[ERROR] 場所: クラス Utils
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :utils
```

**Comment by soudegesu** [comment]
`sun.misc` パッケージにアクセスできないようだ

**Comment by soudegesu** [comment]
まず、そもそもIntelliJでちゃんとクラスが解決できていないようだ

**Comment by soudegesu** [comment]
IntelliJ Ideaの最新版(ideaIO-2017.3.dmg)をインストールすることにした

**Comment by soudegesu** [comment]
バージョンアップしたら、IntelliJの[Preference]>[Build,Excution,Deployment]>[Compiler]>[Java Compiler]の[Project bytecode version]に"9"が追加されていたので、追加して、apply

**Comment by soudegesu** [comment]
Project Settingsを見たら `Language Level`が `8` になっていたので、`9`へ変更

**Comment by soudegesu** [comment]
intelliJのPreferenceを見たら、jdkぽいライブラリが見当たらなかったので、もう一度jdk9をimportしなおしたら解決した

**Comment by soudegesu** [comment]
話を戻して
以下のように変更すると、コンパイルが通った
```
Base64.getEncoder().encodeToString(content.getBytes())
```

**Comment by soudegesu** [comment]
もう一度 `mvn clean install` を行う

**Comment by soudegesu** [comment]
今度はsuccessした

**Comment by soudegesu** [comment]
`mvn clean test` を実行する

**Comment by soudegesu** [comment]
testは成功したが、WARNINGが出力された
```
ARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Resolved (file:/Users/XXXX/.m2/repository/net/bytebuddy/byte-buddy/1.4.26/byte-buddy-1.4.26.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Resolved
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
T
```

**Comment by soudegesu** [comment]
`monitor.utils` module の `pom.xml` に以下を追記
```
	<profiles>
		<profile>
			<id>java-9</id>
			<activation>
				<jdk>9</jdk>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-surefire-plugin</artifactId>
						<configuration>
							<argLine>
								--add-opens java.base./java.lang=ALL-UNNAMED
							</argLine>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
```

※ちなみにsure-fire-pluginはmavenのテスト実行時にレポートを出力してくれるpluginのこと
http://maven.apache.org/surefire/maven-surefire-plugin/

**Comment by soudegesu** [comment]
もう一度 `mvn clean test` を実行する

**Comment by soudegesu** [comment]
パッケージを `ALL-UNNAMED` に指定することで、作成したクラスに対してアクセスできるようにできるようにしているらしい。

**Comment by soudegesu** [comment]
外部に公開する場合には
```
--add-opens java.base/java.lang=ALL-UNNAMED
```
を
```
--add-exports java.base/java.lang=ALL-UNNAMED
```
的な感じにすると良いらしい

**Comment by soudegesu** [comment]
mockitoなどでリフレクション等をやっている場合には
`--illegal-access=deny` オプションを指定してあげると良い

**Comment by soudegesu** [comment]
parent/pom.xml の mockito のバージョンを`2.8.47`へアップデートする

**Comment by soudegesu** [comment]
基本的にはJava9に対応したバージョンに依存ライブラリのバージョンもアップすべきである、とのこおと

**Comment by soudegesu** [comment]
プロジェクトルートに戻って、全体をリビルドしてみる
```
cd ../
mvn clean install
```

**Comment by soudegesu** [comment]
javax.annotationでエラーが出ているようだ
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project rest: Compilation failure: Compilation failure: 
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/MonitorServer.java:[9,16] エラー: パッケージjavax.xml.bindは表示不可です
[ERROR]   (パッケージjavax.xml.bindはモジュールjava.xml.bindで宣言されていますが、モジュール・グラフにありません)
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/MonitorServer.java:[10,16] エラー: パッケージjavax.xml.bindは表示不可です
[ERROR]   (パッケージjavax.xml.bindはモジュールjava.xml.bindで宣言されていますが、モジュール・グラフにありません)
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/MonitorServer.java:[11,16] エラー: パッケージjavax.xml.bindは表示不可です
[ERROR]   (パッケージjavax.xml.bindはモジュールjava.xml.bindで宣言されていますが、モジュール・グラフにありません)
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/StatisticsEntity.java:[6,23] エラー: シンボルを見つけられません
[ERROR]   シンボル:   クラス Generated
[ERROR]   場所: パッケージ javax.annotation
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/StatisticsEntity.java:[7,21] エラー: パッケージjavax.xml.bind.annotationは表示不可です
[ERROR]   (パッケージjavax.xml.bind.annotationはモジュールjava.xml.bindで宣言されていますが、モジュール・グラフにありません)
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/StatisticsEntity.java:[8,21] エラー: パッケージjavax.xml.bind.annotationは表示不可です
[ERROR]   (パッケージjavax.xml.bind.annotationはモジュールjava.xml.bindで宣言されていますが、モジュール・グラフにありません)
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/StatisticsEntity.java:[9,21] エラー: パッケージjavax.xml.bind.annotationは表示不可です
[ERROR]   (パッケージjavax.xml.bind.annotationはモジュールjava.xml.bindで宣言されていますが、モジュール・グラフにありません)
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/StatisticsEntity.java:[16,1] エラー: シンボルを見つけられません
[ERROR]   シンボル: クラス Generated
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

```

**Comment by soudegesu** [comment]
Java EE モジュールはexcludeされているため、必要であれば `--add-module` してあげる必要がある

**Comment by soudegesu** [comment]
monitor.rest/pom.xml に以下を記載
```	
	<profiles>
		<profile>
			<id>java-9</id>
			<activation>
				<jdk>9</jdk>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-compiler-plugin</artifactId>
						<configuration>
							<compilerArgs>
								<arg>--add-modules=java.xml.bind</arg>
							</compilerArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
```

**Comment by soudegesu** [comment]
ビルドがこけてしまう
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project rest: Compilation failure: Compilation failure: 
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/StatisticsEntity.java:[6,23] エラー: シンボルを見つけられません
[ERROR]   シンボル:   クラス Generated
[ERROR]   場所: パッケージ javax.annotation
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/StatisticsEntity.java:[16,1] エラー: シンボルを見つけられません
[ERROR]   シンボル: クラス Generated
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by soudegesu** [comment]
これをオススメされた
https://news.mynavi.jp/article/jsr-16/
```
		<dependency>
			<groupId>com.google.code.findbugs</groupId>
			<artifactId>jsr305</artifactId>
		</dependency>

```

**Comment by soudegesu** [comment]
```
							<compilerArgs>
								<arg>--add-modules</arg><arg>java.xml.bind</arg>
								<arg>--add-modules</arg><arg>java.xml.ws.annotation</arg>
							</compilerArgs>

```
これに変更して `mvn clean install`

**Comment by soudegesu** [comment]
```
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/MonitorServer.java:[8,23] エラー: シンボルを見つけられません
[ERROR]   シンボル:   クラス Nonnull
[ERROR]   場所: パッケージ javax.annotation
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/MonitorServer.java:[27,37] エラー: シンボルを見つけられません
[ERROR]   シンボル:   クラス Nonnull
[ERROR]   場所: クラス MonitorServer
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/MonitorServer.java:[26,2] エラー: シンボルを見つけられません
[ERROR]   シンボル:   クラス Nonnull
[ERROR]   場所: クラス MonitorServer
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/MonitorServer.java:[31,2] エラー: シンボルを見つけられません
[ERROR]   シンボル:   クラス Nonnull
[ERROR]   場所: クラス MonitorServer
[ERROR] /Users/takaaki-suzuki/workspace/demo-java-9-migration/monitor.rest/src/main/java/monitor/rest/MonitorServer.java:[71,2] エラー: シンボルを見つけられません
[ERROR]   シンボル:   クラス Nonnull
[ERROR]   場所: クラス MonitorServer
[ERROR] -> [Help 1]

```

**Comment by soudegesu** [comment]
されにこれで実行する
```
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<compilerArgs>
						<arg>--add-modules</arg><arg>java.xml.bind</arg>
						<arg>--add-modules</arg><arg>java.xml.ws.annotation</arg>
						<arg>--patch-module</arg><arg>java.xml.ws.annotation=${settings.localRepository}/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar</arg>
					</compilerArgs>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

`--patch-module` は既存のjarに特定のモジュールをjarにmergeして使いたい時に指定する
`--upgrade-module-path` はモジュールの変わりに特定のjarを使用したい時に指定する

**Comment by soudegesu** [comment]
ぬるぽになった(これは動画の結果と違う)
```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project rest: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile failed.: NullPointerException -> [Help 1]
[E
```

**Comment by soudegesu** [comment]
maven-compiler-plugin のバージョンを `3.7.0` -> `3.6.1` にダウングレードしたら動いた

**Comment by soudegesu** [comment]
```
cd ../
mvn clean install
```
したらsuccessした

**Comment by soudegesu** [comment]
java cpする
```
java -cp 'monitor/target/libs/*':'monitor/target/main-1.0-SNAPSHOT.jar' monitor.Main
```

**Comment by soudegesu** [comment]
java8 なので怒られた

**Comment by soudegesu** [comment]
一度java9にexportしよう
```
export JAVA_HOME=`/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java_home -v "9"`
```

**Comment by soudegesu** [comment]
```
java -version

java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

**Comment by soudegesu** [comment]
もう一度実行する
```
java -cp 'monitor/target/libs/*':'monitor/target/main-1.0-SNAPSHOT.jar' monitor.Main

Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at monitor.Main.logClassPathContent(Main.java:46)
        at monitor.Main.main(Main.java:28)
```

**Comment by soudegesu** [comment]
`ClassLoader` から `URLClassLoader` にcastできないらしい

**Comment by soudegesu** [comment]
type hierarchy を見ると `SecureClassLoader` とか、色々いる

**Comment by soudegesu** [comment]
もう一度 `java cp` する
```
java -cp 'monitor/target/libs/*':'monitor/target/main-1.0-SNAPSHOT.jar' monitor.Main 

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at monitor.Main.main(Main.java:32)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 1 more
```

**Comment by soudegesu** [comment]
add moduleして実行する
```
java --add-modules java.xml.bind -cp 'monitor/target/libs/*':'monitor/target/main-1.0-SNAPSHOT.jar' monitor.Main
```

**Comment by soudegesu** [comment]
次にプロジェクトをmodule化してみる

**Comment by soudegesu** [comment]
```
javac -version
```

**Comment by soudegesu** [comment]
ブランチを切り替える
```
git checkout migrated
mvn clean install
```

successした

**Comment by soudegesu** [comment]
```
./compile.sh
```

**Comment by soudegesu** [comment]
ビルドが成功し、プロジェクトルートに`build` ディレクトリが生成された

**Comment by soudegesu** [comment]
次に `run.sh` を実行する

**Comment by soudegesu** [comment]
`jdepth` で依存関係を確認する

```
jdeps -s -R -cp 'monitor/target/libs/*' monitor/target/main-1.0-SNAPSHOT.jar  
```

**Comment by soudegesu** [comment]
こんなのが出た
```
分割パッケージ: javax.annotation [jrt:/java.xml.ws.annotation, monitor/target/libs/jsr305-3.0.2.jar]
```

**Comment by soudegesu** [comment]
monitorパッケージのだけ確認する
```
jdeps -s -R -include 'monitor.*' -cp 'monitor/target/libs/*' monitor/target/main-1.0-SNAPSHOT.jar  
```

**Comment by soudegesu** [comment]
dotファイルに出力しなおす
```
jdeps -s -R -include 'monitor.*' --dot-output . -cp 'monitor/target/libs/*' monitor/target/main-1.0-SNAPSHOT.jar     
```

**Comment by soudegesu** [comment]
```
dot -Tpng -O summary.dot  
```

**Comment by soudegesu** [comment]
`monitor.utils`の パッケージルートに `module-info.java` ファイルを置く

```
module monitor.utils {
    // requires
    exports monitor.utils;
}
```

**Comment by soudegesu** [comment]
jarをmodule-pathに出力し、`--add-modules` で利用するmoduleを明示してあげる必要がある

**Comment by soudegesu** [comment]
使用するmoduleのpath指定と使用するmoduleの指定
```
javac \
	--class-path 'build/class-path/*' \
	--module-path build/module-path \
	--add-modules monitor.utils \
```

**Comment by soudegesu** [comment]
これでまた　`./compile.sh` を実行する

**Comment by soudegesu** [comment]
成功した

**Comment by soudegesu** [comment]
`./run.sh` も修正する

**Comment by soudegesu** [comment]
成功した

**Comment by soudegesu** [comment]
今度は `monitor.observer` にmodule-info.java を作成する

```
module monitor.observer {
    exports monitor.observer;
}
```

**Comment by soudegesu** [comment]
`monitor.observer.alpha` にも module-info.java を作成する

```
module monitor.observer.alpha {
    requires monitor.observer;
    exports monitor.observer.alpha;
}
```

**Comment by soudegesu** [comment]
`monitor.observer.beta`にもmodule-info.javaを作成する
```
module monitor.observer.beta {
    requires monitor.observer;
    exports monitor.observer.beta;
}
```

**Comment by soudegesu** [comment]
`./compile.sh` のmodule-pathを変更する

**Comment by soudegesu** [comment]
これを追記
```
	--add-modules monitor.observer.alpha,monitor.observer.beta \
```

**Comment by soudegesu** [comment]
`run.sh` にも同様に追記

**Comment by soudegesu** [comment]
`module-info.java` requires を記載すれば、javac で --module-path を指定しなくてよい、ということなのか？？

**Comment by soudegesu** [comment]
ぽい

**Comment by soudegesu** [comment]
`module-info.java` には直接的に依存するmoduleを全て書いてあげる必要がある

**Comment by soudegesu** [comment]
`--patch-module ` はmodule-info.javaには書けないっぽい

**Comment by soudegesu** [comment]
`monitor.rest`もmodule化して `./compile.sh` する
```
monitor.rest/src/main/java/module-info.java:2: 警告:[removal] モジュールjava.xml.bindは推奨されておらず、削除用にマークされています
    requires java.xml.bind;
                     ^
monitor.rest/src/main/java/module-info.java:3: 警告:[removal] モジュールjava.xml.ws.annotationは推奨されておらず、削除用にマークされています
    requires java.xml.ws.annotation;
                        ^
警告2個

```

**Comment by soudegesu** [comment]
`open module monitor.rest` にしてあげると全てのpackageがopenになるらしい

**Comment by soudegesu** [comment]
module-pathから必要なモジュールを利用することは理解できたが、class-pathの中のjarはロードされるのよね？？
